package slimeknights.mantle.data;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.server.packs.resources.ResourceManager;

import javax.annotation.Nullable;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 * Stand-in for Forge's {@code net.minecraftforge.common.data.ExistingFileHelper}, which datagen
 * providers take to check for and read files from existing packs.
 *
 * <p>PORT: at runtime every caller passes null and reads through a {@link ResourceManager}
 * instead; this type exists so the datagen signatures survive unchanged. The phase-7 datagen
 * round backs it with the real pack list; until then it can wrap a resource manager directly.
 */
public class ExistingFileHelper {
  @Nullable
  private final ResourceManager clientResources;
  @Nullable
  private final ResourceManager serverData;

  public ExistingFileHelper(@Nullable ResourceManager clientResources, @Nullable ResourceManager serverData) {
    this.clientResources = clientResources;
    this.serverData = serverData;
  }

  @Nullable
  private ResourceManager manager(PackType packType) {
    return packType == PackType.CLIENT_RESOURCES ? clientResources : serverData;
  }

  /** Checks whether the given resource exists in the known packs */
  public boolean exists(ResourceLocation loc, PackType packType) {
    ResourceManager manager = manager(packType);
    return manager != null && manager.getResource(loc).isPresent();
  }

  /** Checks whether the given resource exists, building the path from prefix and suffix */
  public boolean exists(ResourceLocation loc, PackType packType, String pathSuffix, String pathPrefix) {
    return exists(ResourceLocation.fromNamespaceAndPath(loc.getNamespace(), pathPrefix + "/" + loc.getPath() + pathSuffix), packType);
  }

  /** Gets the given resource, throwing if missing */
  public Resource getResource(ResourceLocation loc, PackType packType) throws IOException {
    ResourceManager manager = manager(packType);
    if (manager == null) {
      throw new FileNotFoundException("No resource manager for " + packType + "; cannot read " + loc);
    }
    return manager.getResource(loc).orElseThrow(() -> new FileNotFoundException(loc.toString()));
  }

  /** Gets the given resource, building the path from prefix and suffix */
  public Resource getResource(ResourceLocation loc, PackType packType, String pathSuffix, String pathPrefix) throws IOException {
    return getResource(ResourceLocation.fromNamespaceAndPath(loc.getNamespace(), pathPrefix + "/" + loc.getPath() + pathSuffix), packType);
  }

  /** Marks a resource as generated by this run, so later existence checks pass. No-op until phase 7 needs tracking. */
  public void trackGenerated(ResourceLocation loc, PackType packType, String pathSuffix, String pathPrefix) {}

  /** Checks whether the given resource exists, expanding the path through the type */
  public boolean exists(ResourceLocation loc, ResourceType type) {
    return exists(loc, type.packType(), type.suffix(), type.prefix());
  }

  /** Gets the given resource, expanding the path through the type */
  public Resource getResource(ResourceLocation loc, ResourceType type) throws IOException {
    return getResource(loc, type.packType(), type.suffix(), type.prefix());
  }

  /** Marks a resource as generated, expanding the path through the type. No-op until phase 7 needs tracking. */
  public void trackGenerated(ResourceLocation loc, ResourceType type) {}

  /** Pack type plus the path pieces around an id, mirroring Forge's nested type of the same name */
  public record ResourceType(PackType packType, String suffix, String prefix) {}
}
